### ISSUE TITLE
paddhub 使用官方测试代码，ernie 报错

### ISSUE THREAD

**Issue by goheavenz** [PaddlePaddle/PaddleHub#99]
```
module = hub.Module(name="ernie")
dataset = hub.dataset.ChnSentiCorp()

```

-----------------------------------------------
```
2019-08-01 15:27:06,197-INFO: Installing ernie module
2019-08-01 15:27:06,272-ERROR: Can't find module ernie
```
---------------------------------------------------------------------------NameError                                 ```
Traceback (most recent call last)<ipython-input-2-45871eff7b3a> in <module>
----> 1 module = hub.Module(name="ernie")
      2 dataset = hub.dataset.ChnSentiCorp()
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py in __init__(self, name, module_dir, signatures, module_info, assets, processor, extra_info, version)
    120         # TODO(wuzewu): print more module loading info log
    121         if name:
--> 122             self._init_with_name(name=name, version=version)
    123         elif module_dir:
    124             self._init_with_module_file(module_dir=module_dir[0])
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py in _init_with_name(self, name, version)
    148         if not result:
    149             logger.error(tips)
--> 150             exit(1)
    151         logger.info(tips)
    152         self._init_with_module_file(module_dir[0])
NameError: name 'exit' is not defined
```

**Comment by Steffy-zxf** [comment]
感谢反馈！麻烦根据以下链接所指问题，确认是否可以访问外网。
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-FAQ#%E9%97%AE%E9%A2%98%E5%9B%9B

**Comment by goheavenz** [comment]
试过了可以
我是直接用  aistudio  算力卡的GPU 的。

**Comment by goheavenz** [comment]
![TIM截图20190801180813](https://user-images.githubusercontent.com/1908365/62285012-620b4080-b487-11e9-8a9c-e1e1e6517545.png)

**Comment by Steffy-zxf** [comment]
麻烦再尝试下。看错误信息，挂在了python内置函数中。

**Comment by goheavenz** [comment]
可以了，感谢~

**Comment by Gaozhen0816** [comment]
我也遇到同样的问题。@Steffy-zxf 你们给的demo代码不正确，初始环境里没有ernie，应该加一句!hub install ernie

**Comment by Steffy-zxf** [comment]
@Gaozhen0816 感谢反馈！demo里面hub.Module(name="ernie")会自动加载Ernie，和hub install ernie 的效果是一样的。可以将paddlehub升级至最新版，pip install --upgrade paddlehub
